### ISSUE TITLE
Move API credentials to the config.yml file 

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-splunk#715]
Hi team,

We need to improve the way we manage the Wazuh API entries. We should simplify it adding them to the config.yml file. 

**Proposal**

- It would be an array, each element has URL, port, username, password. 
- The user fills that information, something similar to kibana.yml file.
- The app must show clear instructions if it's started with no API entries.

```yaml
api:
  - production_env:
      url: http://172.16.1.2
      port: 55000
      username: foo
      password: bar
  - staging_env:
      url: http://localhost
      port: 7600
      username: fuzz
      password: fuzz
```

**Other related changes**

The above change implies some other modifications such as:
- The kvStore logic must be reviewed, no longer needed.
- Cluster current status is now different, we must reduce and simplify the way we determine if the cluster is enabled or not.
- Settings view, the form, and all related views must be modified.
