### ISSUE TITLE
"Unreachable API" error when configuring Wazuh API for Splunk

### ISSUE THREAD

**Issue by DecafAdmin** [wazuh/wazuh-splunk#942]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 3.13.x   | 8.1.0     | 444 |

**Description**
I get an error "Unreachable API, please check the URL and port." when configuring Wazuh for Splunk app with default API settings on a fresh install.

Setting the URL to https:// gives an error saying 'data'

The wazuh-manager service is running and the splunk service is running

**Screenshots**
![image](https://user-images.githubusercontent.com/74014326/98273903-cc4f4280-1f60-11eb-8b87-55b0fb1e9958.png)
![image](https://user-images.githubusercontent.com/74014326/98274045-f7399680-1f60-11eb-9c0c-3ef7638ef3fe.png)

**Additional context**
Running on Debian 10.6
Followed the guide at [wazuh's official documentation](https://documentation.wazuh.com/4.0/installation-guide/more-installation-alternatives/splunk/splunk-app.html#splunk-app)

**Comment by DecafAdmin** [comment]
I modified the API configuration file in {WAZUH_PATH}/api/configuration/api.yaml by setting
`https:`
  `enabled: no`
After that, I still receive the 'data' response when clicking "Save" in the Wazuh app.
Changing the port to a different value like 55005 gives me the same response.

**Comment by hanschl** [comment]
| Wazuh App | Wazuh Manager | Splunk | Rev |
| --------- | ------------- | ------ | --- |
| 3.13.2| 4.0.0-1 | 8.0.2.1 | 444 |

Hi,

we are having the same problem with the app. After I updated the wazuh-manager to verion 4.0 and configured the api I can't log in from the splunk app anymore.

When I'm trying to connect the api.log shows the following messages:

```
2020/11/09 10:25:17 INFO: unknown_user *** "GET /agents/000" done in 1376.9999999785796ms: 404
2020/11/09 10:25:17 INFO: unknown_user *** "GET /cluster/status" done in 152.99999999115244ms: 401
2020/11/09 10:25:17 INFO: unknown_user *** "GET /cluster/node" done in 8.999999961815774ms: 404
2020/11/09 10:25:17 INFO: unknown_user *** "GET /version" done in 7.000000041443855ms: 404
```

So it seems like the api call isn't correct. 

Here is our api.yaml:

```
# USE THIS FILE AS A TEMPLATE. UNCOMMENT LINES TO APPLY CUSTOM CONFIGURATION

host: ***
port: ***

# Set this option to "yes" in case the API is running behind a proxy server. Values: yes, no
# behind_proxy_server: no

# Advanced configuration

https:
 enabled: yes
 key: "/var/ossec/api/configuration/ssl/wildcard_sha256.key"
 cert: "/var/ossec/api/configuration/ssl/wildcard_sha256.crt"
 use_ca: no
 ca: "/var/ossec/api/configuration/ssl/Corporate_DC_CA.crt"

# Logging configuration
# Values for API log level: disabled, info, warning, error, debug, debug2 (each level includes the previous level).
logs:
 level: "info"
 path: "logs/api.log"

# Cross-origin resource sharing: https://github.com/aio-libs/aiohttp-cors#usage
# cors:
#  enabled: no
#  source_route: "*"
#  expose_headers: "*"
#  allow_headers: "*"
#  allow_credentials: no

# Cache (time in seconds)
# cache:
#  enabled: yes
#  time: 0.750

# Access parameters
access:
 max_login_attempts: 5
 block_time: 1800
 max_request_per_minute: 300

# Force the use of authd when adding and removing agents. Values: yes, no
use_only_authd: no

# Drop privileges (Run as ossec user)
drop_privileges: yes

# Enable features under development
experimental_features: no
```

I've followed the documentation and created a new API User after I've upgrade to wazuh 4.0:

```
 curl -k -X GET "https://***:***/security/users?pretty=true" -H  "Authorization: Bearer $TOKEN"  -H  "Content-Type: application/json"
{
   "data": {
      "affected_items": [
         {
            "id": 1,
            "username": "wazuh",
            "allow_run_as": true,
            "roles": [
               1
            ]
         },
         {
            "id": 2,
            "username": "wazuh-wui",
            "allow_run_as": true,
            "roles": [
               1
            ]
         },
         {
            "id": 100,
            "username": "splunk",
            "allow_run_as": false,
            "roles": [
               1
            ]
         }
      ],
      "total_affected_items": 3,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "All specified users were returned",
   "error": 0
```
If I try calling the api with **http** I'm getting the following error:
![image](https://user-images.githubusercontent.com/68237718/98526790-7e954b80-227a-11eb-8f13-be511c1bf2cf.png)
And when I try calling the api with **https** I'm getting the following error:
![image](https://user-images.githubusercontent.com/68237718/98526868-979dfc80-227a-11eb-88e6-1e5dd30ad03d.png)
